# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
services:  
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: homolog123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
      
  #API Service
  ecommerce-checkout:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ecommerce
      SPRING_DATASOURCE_PASSWORD: homolog123     
  
